# MobileTina release hardening.

-keep,allowoptimization,allowobfuscation class com.v2ray.ang.dto.**
-keepclassmembers class com.v2ray.ang.dto.** {
    <fields>;
}

-keep,allowobfuscation enum com.v2ray.ang.enums.**
-keepclassmembers enum com.v2ray.ang.enums.** {
    <fields>;
}

-keepattributes Signature,*Annotation*
-keep class * extends com.google.gson.reflect.TypeToken

-keepnames class * extends androidx.work.ListenableWorker
-keepclassmembers class * extends androidx.work.ListenableWorker {
    public <init>(android.content.Context, androidx.work.WorkerParameters);
}

# AndroidLibXrayLite is generated by gomobile and uses Java callbacks from native code.
-keep class go.** { *; }
-keep class libv2ray.** { *; }
-keep class * implements libv2ray.CoreCallbackHandler { *; }
-keep class * implements libv2ray.ProcessFinder { *; }

# hev-socks5-tunnel JNI bridge.
-keep class com.v2ray.ang.service.TProxyService { *; }

-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}

-keepclassmembers class * implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator CREATOR;
}
